import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../globals.css";
import Footer from "./common/layout/footer";
import Header from "./common/layout/Header.layout";
import Navbar from "./common/layout/navbar";
import ProductSearchProvider from "./common/provider/ProductSearch.provider";


const lato = Lato({
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${lato.className} antialiased`}
      >
        <ProductSearchProvider>
          <Header />
          <Navbar />
          {children}
          <Footer />
        </ProductSearchProvider>
      </body>
    </html>
  );
}
